version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "13:00"
    open-pull-requests-limit: 1
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
    open-pull-requests-limit: 1
