name: 'OPG Infrastructure Costing'
description: 'Generate high level costing report for AWS accounts'
inputs:
  arn:
    required: true
    description: 'The AWS ARN string to fetch cost data for'
  label:
    required: true
    description: 'A label to attach to the cost data for grouping'
  region:
    default: 'eu-west-1'
    description: 'AWS region'
  months:
    default: 6
    description: Number of months to include in the report
  report:
    default: false
    description: 'If set to true, generate a single combined markdown files out of the raw data files stored in $directory'
  directory:
    required: true
    default: ${{ github.workspace }}

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--arn=${{ inputs.arn }}"
    - "--label=${{ inputs.label }}"
    - "--default=${{ inputs.default }}"
    - "--months=${{ inputs.months }}"
    - "--generate-report=${{ inputs.report }}"
    - "--prefix=${{ github.run_id }}-${{ github.run_number }}"
