name: 'OPG Infrastructure Costing'
description: 'Send cost data for this service to metrics api'
inputs:
  arn:
    required: true
    description: 'The AWS ARN string to fetch cost data for'
  region:
    default: 'eu-west-1'
    description: 'AWS region'
  service:
    required: true
    description: 'Name of the service'
  key:
    required: true
    description: 'The authentication key set as a header for all requests'
  uri:
    required: true
    description: 'The FQDN of the api sending this data to'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--arn=${{ inputs.arn }}"
    - "--service=${{ inputs.service }}"
    - "--region=${{ inputs.region }}"
    - "--key=${{ inputs.key }}"
    - "--uri=${{ inputs.uri }}"
